# Checks client builder for operations for each type of object.
name: operation_check
on: 
  pull_request:
  workflow_dispatch:

jobs:
  check_content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Check for operations which do not have all five CRUD operations (retrieve, create, update, delete, patch)
        run: |
          exit `bin/check-operations.sh`
        shell: bash
